export const graphBrowserPage = String.raw`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EdgeLore Graph Browser</title><style>
:root{color-scheme:light;--bg:#f5f7fa;--panel:#fff;--line:#e1e6ed;--text:#263241;--muted:#748194;--cyan:#83b4d0;--orange:#d5ad79;--green:#91b39a;--red:#c96e75}
*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--text);font:13px/1.45 Inter,ui-sans-serif,system-ui,"Segoe UI",sans-serif}button,input{font:inherit;color:inherit}button{cursor:pointer;background:#fff;border:1px solid #dce2e9;border-radius:6px;padding:7px 10px;box-shadow:0 1px 2px #1c27330a;transition:.15s}button:hover,button.active{border-color:#9aabc0;background:#f0f4f8;color:#263c56}
header{height:54px;display:flex;align-items:center;justify-content:space-between;padding:0 18px;border-bottom:1px solid var(--line);background:#fff}.brand{display:flex;align-items:center;gap:10px}.logo{width:25px;height:25px;display:grid;place-items:center;border-radius:7px;background:linear-gradient(140deg,#e6c6a0,#cc9d79);color:#fff;font-weight:900}.brand strong{font-size:14px;letter-spacing:.03em}.brand small{color:var(--muted);margin-left:8px}.top-right{display:flex;align-items:center;gap:12px;color:var(--muted);font-size:11px}.logout{padding:5px 8px;color:#68778a;font-size:10px}.local{display:flex;align-items:center;gap:6px;color:#648f72}.local i{width:6px;height:6px;border-radius:50%;background:#78ab82;box-shadow:0 0 8px #78ab8255}
.layout{height:calc(100% - 54px);display:grid;grid-template-columns:272px minmax(400px,1fr) 326px}.sidebar,.inspector{background:#fff;min-height:0;display:flex;flex-direction:column}.sidebar{border-right:1px solid var(--line)}.inspector{border-left:1px solid var(--line);overflow:auto}.side-head{padding:16px 14px 11px}.eyebrow{font-size:10px;text-transform:uppercase;letter-spacing:.14em;color:#738095;font-weight:700;margin-bottom:10px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.stat{background:#f8fafc;border:1px solid #e7ebf0;border-radius:6px;padding:7px 5px;text-align:center}.stat b{display:block;font-size:15px;color:#2f3e50}.stat span{font-size:9px;color:var(--muted)}.tabs{display:flex;gap:4px;padding:10px 12px 0}.tabs button{flex:1;padding:7px 4px;background:#f8fafc;color:#68778a;font-size:11px;box-shadow:none}.tabs button.active{background:#edf2f7;color:#34465d;border-color:#cbd5e1}
.search-wrap{padding:10px 12px 8px;position:relative}.search-wrap input{width:100%;background:#fbfcfe;border:1px solid #dbe2e9;border-radius:6px;padding:9px 10px 9px 30px;outline:0}.search-wrap input:focus{border-color:#96aabd;box-shadow:0 0 0 2px #e7edf3}.search-icon{position:absolute;left:22px;top:18px;color:#8290a2}.list-head{display:flex;justify-content:space-between;padding:4px 14px 7px;color:#738095;font-size:10px}.list{overflow:auto;flex:1;padding:0 9px 12px}.item{width:100%;display:block;text-align:left;border:1px solid transparent;background:transparent;padding:8px 9px;margin-bottom:2px;box-shadow:none}.item:hover,.item.selected{background:#f2f5f8;border-color:#e3e8ee}.item .title{font-size:12px;color:#303d4d;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.item .meta{display:flex;justify-content:space-between;gap:6px;margin-top:3px;font-size:10px;color:#788598}.state{font-size:9px;text-transform:uppercase;letter-spacing:.06em}.state.accepted{color:#668f72}.state.tentative{color:#a77c42}.state.conflict{color:#be626b}.more{margin:0 12px 12px;color:#657387}
.center{display:flex;flex-direction:column;min-width:0;min-height:0;background:#fff}.querybar{min-height:58px;display:flex;align-items:center;justify-content:space-between;padding:10px 15px;border-bottom:1px solid var(--line);background:#fff}.focus-name{font-size:13px;font-weight:650;color:#273547}.focus-meta{font-size:10px;color:#768497;margin-top:2px}.controls{display:flex;align-items:center;gap:5px}.controls button{padding:6px 8px;font-size:10px}.controls .expand{color:#587d99;border-color:#cad8e4;margin-left:7px}.canvas{position:relative;flex:1;min-height:0;background-color:#fcfdff;background-image:radial-gradient(#dfe5ec .8px,transparent .8px);background-size:22px 22px;overflow:hidden}#graph{position:absolute;inset:0;z-index:1}.canvas .empty{position:absolute;z-index:2;inset:0;display:grid;place-content:center;text-align:center;color:#7e8a9a;line-height:1.8;pointer-events:none}.legend{height:36px;display:flex;align-items:center;gap:16px;padding:0 15px;border-top:1px solid var(--line);color:#677589;font-size:10px;background:#fff}.legend span{display:flex;align-items:center;gap:6px}.legend i{display:inline-block;width:8px;height:8px;border-radius:50%}.legend .size-hint{color:#8591a0;font-size:9px}.legend .hint{margin-left:auto;color:#8591a0}.toast{position:absolute;z-index:3;bottom:45px;left:50%;transform:translateX(-50%);padding:8px 12px;border:1px solid #d7dfe8;border-radius:7px;background:#fff;color:#3d4c60;font-size:10px;pointer-events:none;opacity:0;transition:.2s;box-shadow:0 4px 18px #1724341a}.toast.show{opacity:1}
.inspect-title{padding:17px 16px 12px;border-bottom:1px solid var(--line)}.inspect-title h2{font-size:14px;margin:0 0 3px;overflow-wrap:anywhere}.inspect-title small{color:#788598}.inspect-body{padding:0 16px 20px}.section-title{font-size:10px;text-transform:uppercase;letter-spacing:.13em;color:#748195;margin:17px 0 8px}.value-box{font-size:16px;line-height:1.4;padding:12px;border:1px solid #e0e6ed;background:#f7f9fb;color:#2e3b4c;border-radius:7px;overflow-wrap:anywhere}.kv{display:grid;grid-template-columns:85px 1fr;gap:8px;padding:8px 0;border-bottom:1px solid #edf0f3}.kv label{font-size:10px;color:#788598}.kv div{font-size:11px;overflow-wrap:anywhere;color:#435166}.episode{padding:10px;margin:6px 0;background:#f3f7fa;border-left:2px solid #86a9c2;border-radius:0 5px 5px 0;white-space:pre-wrap;font-size:11px;color:#415165}.episode-meta{font-size:9px;color:#7b8797;margin-top:8px}.claim-row{width:100%;text-align:left;margin:4px 0;padding:9px;background:#f6f8fa;border-color:#e6ebf0;color:#37475a;box-shadow:none}.conflict-card{border:1px solid #ead4d6;background:#fff9f9;border-radius:7px;padding:10px;margin:8px 0}.conflict-card h4{margin:0 0 8px;color:#b85d65;font-size:11px}.conflict-card .claim-row{font-size:10px}.notice{padding:10px;border:1px solid #eadfc8;background:#fffaf1;color:#876d3d;border-radius:6px;font-size:10px;margin:10px 0}.placeholder{color:#8490a0;text-align:center;padding:24px}
@media(max-width:1050px){.layout{grid-template-columns:190px minmax(0,1fr) 230px}.controls{gap:3px}.controls button{font-size:9px;padding:5px}.querybar{padding:8px}.legend{gap:8px;font-size:9px}.legend .hint{display:none}}@media(max-width:760px){html,body{overflow:auto}.layout{height:auto;min-height:calc(100% - 54px);display:grid;grid-template-columns:1fr}.sidebar{max-height:430px;border-right:0;border-bottom:1px solid var(--line)}.center{height:600px}.inspector{min-height:400px;border-left:0;border-top:1px solid var(--line)}}
</style></head><body><header><div class="brand"><div class="logo">E</div><div><strong>EdgeLore</strong><small>GRAPH BROWSER</small></div></div><div class="top-right"><span id="db-label">LOCAL MEMORY GRAPH</span><span class="local"><i></i>READ ONLY</span><button class="logout" id="logout" type="button">LOG OUT</button></div></header><div class="layout"><aside class="sidebar"><div class="side-head"><div class="eyebrow">Graph overview</div><div class="stats" id="stats"></div></div><div class="tabs"><button class="active" data-kind="slots">Slots</button><button data-kind="entities">Entities</button><button data-kind="conflicts">Conflicts</button></div><div class="search-wrap"><span class="search-icon">⌕</span><input id="search" placeholder="Find a slot, claim or entity" autocomplete="off"></div><div class="list-head"><span id="list-label">SLOTS</span><span id="list-count"></span></div><div class="list" id="list"></div><button class="more" id="more">Load more</button></aside><main class="center"><div class="querybar"><div><div class="focus-name" id="focus">Select a memory node</div><div class="focus-meta" id="focus-meta">Bounded neighborhood · up to 3 hops</div></div><div class="controls"><button data-depth="1">1 HOP</button><button class="active" data-depth="2">2 HOPS</button><button data-depth="3">3 HOPS</button><button class="expand" id="expand">＋ EXPAND</button></div></div><div class="canvas" id="canvas"><div id="graph" aria-label="Memory neighborhood graph"></div><div class="empty">Search and select a Slot, Entity or conflict.<br>The graph opens around that memory, one neighborhood at a time.</div><div class="toast" id="toast"></div></div><div class="legend"><span><i style="background:var(--orange)"></i>Slot</span><span><i style="background:var(--cyan)"></i>Claim</span><span><i style="background:var(--green)"></i>Entity / Event</span><span><i style="background:var(--red)"></i>Conflict</span><span class="size-hint">Node size = local links</span><span class="hint">Drag nodes · scroll to zoom · click to inspect</span></div></main><aside class="inspector" id="inspector"><div class="placeholder">Select a node to inspect its value, provenance, source Episode and relationships.</div></aside></div>
<script src="/assets/cytoscape.js"></script><script>
const $=s=>document.querySelector(s);let kind="slots",offset=0,query="",depth=2,selected=null,selectedConflict=null,itemsTotal=0,cy=null;
async function api(path){const response=await fetch(path);const data=await response.json();if(!response.ok)throw Error(data.error||response.statusText);return data}
function text(tag,value,cls){const el=document.createElement(tag);if(cls)el.className=cls;el.textContent=value??"";return el}
function keyValue(key,value){const row=document.createElement("div");row.className="kv";row.append(text("label",key),text("div",typeof value==="string"?value:JSON.stringify(value??"—")));return row}
function stateClass(value){return value==="conflict"?"conflict":value==="tentative"?"tentative":"accepted"}
function showError(error){const toast=$("#toast");toast.textContent=error.message;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),3500)}
async function loadSummary(){const s=await api("/api/summary");const values=[[s.slots,"SLOTS"],[s.claims,"CLAIMS"],[s.entities,"ENTITIES"],[s.conflicts,"OPEN"]];$("#stats").replaceChildren(...values.map(([n,label])=>{const box=document.createElement("div");box.className="stat";box.append(text("b",n),text("span",label));return box}))}
async function loadList(reset=true){try{if(reset){offset=0;$("#list").replaceChildren()}const suffix="?offset="+offset+"&limit=30&q="+encodeURIComponent(query);const data=await api(kind==="conflicts"?"/api/conflicts"+suffix:"/api/"+kind+suffix);itemsTotal=data.total;$("#list-count").textContent=String(data.total);$("#list-label").textContent=kind.toUpperCase();for(const row of data.items){const button=document.createElement("button");button.className="item";if(kind==="conflicts"){const title=text("div",row.dimensionKey,"title");const meta=text("div",row.incumbents.length+" accepted · "+row.challengers.length+" tentative","meta");button.append(title,meta);button.onclick=()=>openConflict(row)}else{const title=text("div",row.label||row.key||row.type,"title");const meta=document.createElement("div");meta.className="meta";meta.append(text("span",kind==="slots"?row.claimCount+" claims":row.type),text("span",row.state||"open","state "+stateClass(row.state)));button.append(title,meta);button.dataset.id=row.id;button.onclick=()=>selectNode(row.id,row)}$("#list").append(button)}offset+=data.items.length;$("#more").hidden=offset>=itemsTotal;if(reset&&data.items[0]&&kind!=="conflicts")await selectNode(data.items[0].id,data.items[0]);}catch(error){showError(error)}}
function kindLabel(node){if(node.type==="core:dimension")return "SLOT";if(node.type==="core:statement")return "CLAIM";return "ENTITY"}
function edgeLabel(value){return ({"core:about":"ABOUT","core:contradicts":"CONTRADICTS","core:supersedes":"SUPERSEDES","core:refines":"REFINES","core:equivalent_to":"EQUIVALENT","slot:claim":"HAS CLAIM","slot:subject":"SUBJECT SLOT","claim:slot":"IN SLOT"})[value]||value.replace(/^core:/,"").replaceAll("_"," ").toUpperCase()}
function shorten(value,max=22){const s=String(value??"");return s.length>max?s.slice(0,max-1)+"…":s}
async function selectNode(id,row){selected=id;selectedConflict=null;document.querySelectorAll(".item").forEach(el=>el.classList.toggle("selected",el.dataset.id===id));const label=row?.label||row?.key||row?.type||id;$("#focus").textContent=label;await loadNeighborhood(id);if(row?.type==="core:statement")await showClaim(id);else if(row?.type==="core:dimension")showSlot(row);else if(row)showEntity(row)}
async function loadNeighborhood(id){try{const data=await api("/api/neighborhood/"+encodeURIComponent(id)+"?depth="+depth+"&limit=36");$("#focus-meta").textContent=data.nodes.length+" nodes · "+data.edges.length+" relationships · "+depth+" hop"+(depth===1?"":"s")+(data.truncated?" · capped":"");renderGraph(data)}catch(error){showError(error)}}
function renderGraph(data){
  $(".empty")?.remove();
  if(cy){cy.destroy();cy=null}
  const degree=new Map(data.nodes.map(node=>[node.id,0]));
  for(const edge of data.edges){degree.set(edge.from,(degree.get(edge.from)||0)+1);degree.set(edge.to,(degree.get(edge.to)||0)+1)}
  const nodes=data.nodes.map(node=>{const links=degree.get(node.id)||0;return{data:{id:node.id,type:node.type,label:shorten(node.label,28),fullLabel:node.label,state:node.state||"",kind:kindLabel(node),root:node.id===data.rootId?1:0,degree:links,size:Math.min(74,40+links*6)}}});
  const edges=data.edges.map(edge=>({data:{id:edge.id,source:edge.from,target:edge.to,label:edgeLabel(edge.type),type:edge.type}}));
  cy=window.cytoscape({container:$("#graph"),elements:[...nodes,...edges],minZoom:.35,maxZoom:2.5,wheelSensitivity:.18,selectionType:"single",style:[
    {selector:"node",style:{"width":"data(size)","height":"data(size)","background-color":"#bcc6d2","background-opacity":.98,"border-width":1.5,"border-color":"#8997a7","label":"data(label)","color":"#455367","font-size":10,"font-weight":500,"text-wrap":"wrap","text-max-width":112,"text-valign":"bottom","text-halign":"center","text-margin-y":9,"text-background-color":"#ffffff","text-background-opacity":.95,"text-background-padding":3,"text-background-shape":"roundrectangle"}},
    {selector:'node[type="core:dimension"]',style:{"background-color":"#d5ad79","border-color":"#b88c58","shape":"ellipse","label":"data(label)"}},
    {selector:'node[type="core:statement"]',style:{"background-color":"#83b4d0","border-color":"#6696b0","shape":"ellipse"}},
    {selector:'node[type!="core:dimension"][type!="core:statement"]',style:{"background-color":"#91b39a","border-color":"#6e9278","shape":"ellipse"}},
    {selector:'node[state="conflict"]',style:{"border-width":3,"border-color":"#c96e75"}},
    {selector:"node[root = 1]",style:{"border-width":3,"border-color":"#fff","width":"mapData(size,40,74,64,74)","height":"mapData(size,40,74,64,74)","z-index":10,"font-weight":700}},
    {selector:"node:selected",style:{"border-width":3,"border-color":"#46566b","overlay-color":"#dce6ef","overlay-opacity":.25,"overlay-padding":8}},
    {selector:"edge",style:{"width":1.25,"line-color":"#9aa6b4","target-arrow-color":"#8795a5","target-arrow-shape":"triangle","arrow-scale":.8,"curve-style":"bezier","opacity":.85,"label":"data(label)","font-size":8,"color":"#687587","text-rotation":"autorotate","text-background-color":"#ffffff","text-background-opacity":.96,"text-background-padding":3,"text-border-width":1,"text-border-color":"#e4e9ef","text-border-opacity":1}},
    {selector:'edge[type="core:contradicts"]',style:{"line-color":"#c96e75","target-arrow-color":"#c96e75","color":"#ac565e","width":1.8}},
    {selector:'edge[type="core:supersedes"]',style:{"line-color":"#9587ab","target-arrow-color":"#9587ab"}}
  ],layout:{name:"cose",animate:"end",animationDuration:450,fit:true,padding:42,nodeRepulsion:6500,idealEdgeLength:118,edgeElasticity:90,gravity:.24,numIter:650,randomize:true,componentSpacing:85,uniformNodeDimensions:false}});
  cy.on("tap","node",event=>selectFromGraph(event.target.data()));
  const resize=new ResizeObserver(()=>{if(cy)cy.resize()});resize.observe($("#graph"));cy.one("destroy",()=>resize.disconnect());
}
async function selectFromGraph(node){selected=node.id;selectedConflict=null;$("#focus").textContent=node.label;await loadNeighborhood(node.id);if(node.type==="core:statement")await showClaim(node.id);else if(node.type==="core:dimension")showSlot(node);else showEntity(node)}
function setInspector(title,subtitle){const panel=$("#inspector");panel.replaceChildren();const head=document.createElement("div");head.className="inspect-title";head.append(text("h2",title),text("small",subtitle));const body=document.createElement("div");body.className="inspect-body";panel.append(head,body);return body}
function showSlot(row){const body=setInspector(row.label||row.key,"SLOT · core:dimension");const card=document.createElement("div");card.className="value-box";card.textContent=row.label||row.key;body.append(card);body.append(text("div","Slot identity","section-title"),keyValue("Property",row.property_key),keyValue("Subject",row.subject_id),keyValue("State",row.state),keyValue("Claims",row.claimCount??"—"),keyValue("ID",row.id));if(row.latest?.length){body.append(text("div","Recent claims","section-title"));for(const claim of row.latest){const button=document.createElement("button");button.className="claim-row";button.textContent=String(claim.value)+" · "+claim.state+" · "+claim.created_at;button.onclick=()=>showClaim(claim.id);body.append(button)}}}
function showEntity(row){const body=setInspector(row.label||row.key||row.type,"ENTITY / EVENT · "+row.type);body.append(keyValue("Value",row.value),keyValue("Key",row.key),keyValue("State",row.state),keyValue("ID",row.id));body.append(text("div","Connected memories","section-title"),text("p","Click a connected Slot or Claim in the graph to inspect its evidence.","placeholder"))}
async function showClaim(id){try{const data=await api("/api/claims/"+encodeURIComponent(id)),node=data.node,body=setInspector(String(node.value),"CLAIM · "+String(node.state).toUpperCase());const value=document.createElement("div");value.className="value-box";value.textContent=String(node.value)+(node.unit?" "+node.unit:"");body.append(value);body.append(text("div","Claim state & provenance","section-title"),keyValue("Status",node.state),keyValue("Created",node.created_at),keyValue("Updated",node.updated_at),keyValue("Said by",node.saidBy),keyValue("Written by",node.created_by),keyValue("Scope",node.scope),keyValue("Slot",data.slot?.label),keyValue("Source refs",node.source_refs),keyValue("Schema",node.schema_version));body.append(text("div","Source Episodes","section-title"));if(!data.episodes.length)body.append(text("p","No Episode record was retained for this source reference.","placeholder"));for(const episode of data.episodes){for(const turn of episode.turns){const source=text("div",turn.role.toUpperCase()+"  ·  "+turn.content,"episode");body.append(source)}body.append(text("div",episode.id+" · "+episode.created_at+" · "+episode.created_by,"episode-meta"))}body.append(text("div","Relationships & audit","section-title"));if(!data.edges.length)body.append(text("p","No direct relationship or adjudication edge.","placeholder"));for(const edge of data.edges)body.append(keyValue(edgeLabel(edge.type),(edge.from_node?.label||edge.from)+" → "+(edge.to_node?.label||edge.to)+" · "+edge.created_by+" · "+edge.created_at));}catch(error){showError(error)}}
function openConflict(conflict){selectedConflict=conflict;selected=conflict.dimensionId;$("#focus").textContent=conflict.dimensionKey;loadNeighborhood(conflict.dimensionId);const body=setInspector(conflict.dimensionKey,"OPEN CONFLICT · read only");body.append(text("div","Current belief and challenger are shown separately. No resolution action is available here.","notice"),keyValue("Slot ID",conflict.dimensionId));for(const [label,rows]of [["Incumbents · accepted",conflict.incumbents],["Challengers · tentative",conflict.challengers]]){body.append(text("div",label,"section-title"));const box=document.createElement("div");box.className="conflict-card";box.append(text("h4",label));for(const claim of rows){const button=document.createElement("button");button.className="claim-row";button.textContent=JSON.stringify(claim.value)+" · "+claim.createdBy+" · "+claim.createdAt;button.onclick=()=>{selected=claim.statementId;loadNeighborhood(claim.statementId);showClaim(claim.statementId)};box.append(button)}body.append(box)}}
$("#expand").onclick=()=>{if(!selected){showError(Error("Select a node before expanding."));return}if(depth<3){depth++;document.querySelectorAll("[data-depth]").forEach(button=>button.classList.toggle("active",Number(button.dataset.depth)===depth));loadNeighborhood(selected)}};document.querySelectorAll("[data-depth]").forEach(button=>button.onclick=()=>{depth=Number(button.dataset.depth);document.querySelectorAll("[data-depth]").forEach(item=>item.classList.toggle("active",item===button));if(selected)loadNeighborhood(selected)});document.querySelectorAll("[data-kind]").forEach(button=>button.onclick=()=>{document.querySelectorAll("[data-kind]").forEach(item=>item.classList.toggle("active",item===button));kind=button.dataset.kind;loadList()});$("#search").onkeydown=event=>{if(event.key==="Enter"){query=event.target.value.trim();loadList()}};$("#search").oninput=event=>{clearTimeout(window.searchTimer);query=event.target.value.trim();window.searchTimer=setTimeout(()=>loadList(),250)};$("#more").onclick=()=>loadList(false);loadSummary().then(loadList).catch(showError);
</script><script>$("#logout").onclick=async()=>{await fetch("/api/auth/logout",{method:"POST"});location.reload()};</script></body></html>`;
